# Puerto del servidor
server.port=8080

# Rutas de carpetas para mensajes
converter.input-folder=mt-files
converter.output-folder=converted-files

# Configuracion SQLite (crear en carpeta raiz del proyecto)
spring.datasource.url=jdbc:sqlite:conversion_logs.db
spring.datasource.driver-class-name:org.sqlite.JDBC
spring.datasource.initialization-mode=always
spring.datasource.username=eokz_swift
spring.datasource.password=spoonful*2019

# JPA
spring.jpa.database-plataform=org.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging general
logging.file.name=logs/mtmx.log
logging.level.org.springframework=INFO